services:
  app:
    build:
      context: .
    container_name: "app"
    network_mode: "falcon1-network"
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - configs.env
    depends_on:
      - clickhouse
      - mysql

  mysql:
    image: "mysql"
    container_name: "mysql"
    network_mode: "falcon1-network"
    ports:
      - "3306:3306"
    env_file:
      - configs.env
    volumes:
      - ./mysql-data:/var/lib/mysqls

  clickhouse:
    image: "clickhouse/clickhouse-server"
    container_name: "clickhouse"
    network_mode: "falcon1-network"
    ports:
      - "8123:8123"
    env_file:
      - configs.env
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse/
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8123/ping || exit 1
      interval: 2s
      timeout: 2s
      retries: 16
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
